-- dispatch plan
create table DISPATCHSTATIONPLAN
(
  ID NUMBER(11) not null
    primary key,
  GENERATETIMESTAMP VARCHAR2(20),
  PLANKEY VARCHAR2(50)
    unique,
  TRAINNUM VARCHAR2(10),
  UNIQUETRAINNUM VARCHAR2(10),
  TRAINTYPE VARCHAR2(10),
  PLANDATE VARCHAR2(10),
  STATIONTYPE VARCHAR2(10),
  TRAINDIRECTION VARCHAR2(5),
  STARTSTATION VARCHAR2(30),
  FINALSTATION VARCHAR2(30),
  PRESENTSTATION VARCHAR2(30),
  VALIDPERIODSTART VARCHAR2(10),
  VALIDPERIODEND VARCHAR2(10),
  TRAINSUSPENDSTART VARCHAR2(10),
  TRAINSUSPENDEND VARCHAR2(10),
  MANUALSUSPENDFLAG NUMBER(1),
  PLANEDTRACKNUM NUMBER(11),
  ACTUALTRACKNUM NUMBER(11),
  PLANEDDEPARTURETIME VARCHAR2(20),
  ACTUALDEPARTURETIME VARCHAR2(20),
  DEPARTURESTATEREASON VARCHAR2(100),
  PLANEDARRIVETIME VARCHAR2(20),
  ACTUALARRIVETIME VARCHAR2(20),
  ARRIVESTATEREASON VARCHAR2(100),
  LASTEDITEDTIMESTAMP VARCHAR2(20)
)
/

create trigger DISPATCH_TRIGGER
before insert
  on DISPATCHSTATIONPLAN
for each row
  BEGIN
    SELECT DISPATCH_Sequence.nextval
    INTO :New.id
    FROM dual;
  END;
/

-- passenger plan
create table PASSENGERSTATIONPLAN
(
  ID NUMBER(11) not null
    primary key,
  GENERATETIMESTAMP VARCHAR2(20),
  PLANKEY VARCHAR2(50)
    unique,
  TRAINNUM VARCHAR2(10),
  UNIQUETRAINNUM VARCHAR2(10),
  TRAINTYPE VARCHAR2(10),
  PLANDATE VARCHAR2(10),
  STATIONTYPE VARCHAR2(10),
  TRAINDIRECTION VARCHAR2(5),
  STARTSTATION VARCHAR2(30),
  FINALSTATION VARCHAR2(30),
  PRESENTSTATION VARCHAR2(30),
  VALIDPERIODSTART VARCHAR2(10),
  VALIDPERIODEND VARCHAR2(10),
  TRAINSUSPENDSTART VARCHAR2(10),
  TRAINSUSPENDEND VARCHAR2(10),
  MANUALSUSPENDFLAG NUMBER(1),
  PLANEDTRACKNUM NUMBER(11),
  ACTUALTRACKNUM NUMBER(11),
  PLANEDDEPARTURETIME VARCHAR2(20),
  ACTUALDEPARTURETIME VARCHAR2(20),
  DEPARTURESTATEREASON VARCHAR2(100),
  PLANEDARRIVETIME VARCHAR2(20),
  ACTUALARRIVETIME VARCHAR2(20),
  ARRIVESTATEREASON VARCHAR2(100),
  STARTABOARDCHECKBASE VARCHAR2(20),
  STARTABOARDCHECKTIMEOFFSET NUMBER(11),
  STARTABOARDCHECKTIME VARCHAR2(20),
  STOPABOARDCHECKBASE VARCHAR2(20),
  STOPABOARDCHECKTIMEOFFSET NUMBER(11),
  STOPABOARDCHECKTIME VARCHAR2(20),
  WAITZONE VARCHAR2(200) default NULL,
  STATIONENTRANCEPORT VARCHAR2(200) default NULL,
  STATIONEXITPORT VARCHAR2(200) default NULL,
  ABOARDCHECKGATE VARCHAR2(200) default NULL,
  EXITCHECKGATE VARCHAR2(200) default NULL,
  LASTEDITEDTIMESTAMP VARCHAR2(20)
)
/

create trigger PASSENGER_TRIGGER
before insert
  on PASSENGERSTATIONPLAN
for each row
  BEGIN
    SELECT PASSENGER_Sequence.nextval
    INTO :New.id
    FROM dual;
  END;
/

-- guide plan
create table GUIDESTATIONPLAN
(
  ID NUMBER(11) not null
    primary key,
  GENERATETIMESTAMP VARCHAR2(20),
  PLANKEY VARCHAR2(50)
    unique,
  TRAINNUM VARCHAR2(10),
  UNIQUETRAINNUM VARCHAR2(10),
  TRAINTYPE VARCHAR2(10),
  PLANDATE VARCHAR2(10),
  STATIONTYPE VARCHAR2(10),
  TRAINDIRECTION VARCHAR2(5),
  STARTSTATION VARCHAR2(30),
  FINALSTATION VARCHAR2(30),
  PRESENTSTATION VARCHAR2(30),
  VALIDPERIODSTART VARCHAR2(10),
  VALIDPERIODEND VARCHAR2(10),
  TRAINSUSPENDSTART VARCHAR2(10),
  TRAINSUSPENDEND VARCHAR2(10),
  MANUALSUSPENDFLAG NUMBER(1),
  PLANEDTRACKNUM NUMBER(11),
  ACTUALTRACKNUM NUMBER(11),
  PLANEDDEPARTURETIME VARCHAR2(20),
  ACTUALDEPARTURETIME VARCHAR2(20),
  DEPARTURESTATEREASON VARCHAR2(100),
  PLANEDARRIVETIME VARCHAR2(20),
  ACTUALARRIVETIME VARCHAR2(20),
  ARRIVESTATEREASON VARCHAR2(100),
  STARTABOARDCHECKBASE VARCHAR2(20),
  STARTABOARDCHECKTIMEOFFSET NUMBER(11),
  STARTABOARDCHECKTIME VARCHAR2(20),
  STOPABOARDCHECKBASE VARCHAR2(20),
  STOPABOARDCHECKTIMEOFFSET NUMBER(11),
  STOPABOARDCHECKTIME VARCHAR2(20),
  WAITZONE VARCHAR2(200) default NULL,
  STATIONENTRANCEPORT VARCHAR2(200) default NULL,
  STATIONEXITPORT VARCHAR2(200) default NULL,
  ABOARDCHECKGATE VARCHAR2(200) default NULL,
  EXITCHECKGATE VARCHAR2(200) default NULL,
  LASTEDITEDTIMESTAMP VARCHAR2(20)
)
/

create trigger GUIDE_TRIGGER
before insert
  on GUIDESTATIONPLAN
for each row
  BEGIN
    SELECT GUIDE_Sequence.nextval
    INTO :New.id
    FROM dual;
  END;
/

-- broadcast plan
create table BROADCASTSTATIONPLAN
(
  ID NUMBER(11) not null
    primary key,
  GENERATETIMESTAMP VARCHAR2(20),
  PLANKEY VARCHAR2(50)
    unique,
  TRAINNUM VARCHAR2(10),
  UNIQUETRAINNUM VARCHAR2(10),
  TRAINTYPE VARCHAR2(10),
  PLANDATE VARCHAR2(10),
  STATIONTYPE VARCHAR2(10),
  TRAINDIRECTION VARCHAR2(5),
  STARTSTATION VARCHAR2(30),
  FINALSTATION VARCHAR2(30),
  PRESENTSTATION VARCHAR2(30),
  VALIDPERIODSTART VARCHAR2(10),
  VALIDPERIODEND VARCHAR2(10),
  TRAINSUSPENDSTART VARCHAR2(10),
  TRAINSUSPENDEND VARCHAR2(10),
  MANUALSUSPENDFLAG NUMBER(1),
  PLANEDTRACKNUM NUMBER(11),
  ACTUALTRACKNUM NUMBER(11),
  PLANEDDEPARTURETIME VARCHAR2(20),
  ACTUALDEPARTURETIME VARCHAR2(20),
  DEPARTURESTATEREASON VARCHAR2(100),
  PLANEDARRIVETIME VARCHAR2(20),
  ACTUALARRIVETIME VARCHAR2(20),
  ARRIVESTATEREASON VARCHAR2(100),
  STARTABOARDCHECKBASE VARCHAR2(20),
  STARTABOARDCHECKTIMEOFFSET NUMBER(11),
  STARTABOARDCHECKTIME VARCHAR2(20),
  STOPABOARDCHECKBASE VARCHAR2(20),
  STOPABOARDCHECKTIMEOFFSET NUMBER(11),
  STOPABOARDCHECKTIME VARCHAR2(20),
  WAITZONE VARCHAR2(200) default NULL,
  STATIONENTRANCEPORT VARCHAR2(200) default NULL,
  STATIONEXITPORT VARCHAR2(200) default NULL,
  ABOARDCHECKGATE VARCHAR2(200) default NULL,
  EXITCHECKGATE VARCHAR2(200) default NULL,
  BROADCASTKIND VARCHAR2(20),
  BROADCASTBASETIME VARCHAR2(20),
  BROADCASTTIMEOFFSET NUMBER(11),
  BROADCASTTIME VARCHAR2(20),
  BROADCASTCONTENTNAME VARCHAR2(50),
  BROADCASTOPERATIONMODE VARCHAR2(10),
  BROADCASTPRIORITYLEVEL NUMBER(11),
  BROADCASTAREA VARCHAR2(200),
  BROADCASTSTATE VARCHAR2(20),
  LASTEDITEDTIMESTAMP VARCHAR2(20)
)
/

create trigger BROADCAST_SEQUENCE
before insert
  on BROADCASTSTATIONPLAN
for each row
  BEGIN
    SELECT BROADCAST_Sequence.nextval
    INTO :New.id
    FROM dual;
  END;
/


-- OrganizeTemplate  todo 需要添加sequence和trigger
create table OrganizeTemplate
(
  ID number(11) not null primary key,
  TRAINNUM VARCHAR2(10),
  STATIONNAME VARCHAR2(10),
  STARTABOARDCHECKBASE VARCHAR2(20),
  STARTABOARDCHECKTIMEOFFSET number(11),
  STOPABOARDCHECKBASE VARCHAR2(20),
  STOPABOARDCHECKTIMEOFFSET number(11),
  WAITZONELIST VARCHAR2(200) default NULL,
  STATIONENTRANCEPORT VARCHAR2(200) default NULL,
  STATIONEXITPORT VARCHAR2(200) default NULL,
  ABOARDCHECKGATE VARCHAR2(200) default NULL,
  EXITCHECKGATE VARCHAR2(200) default NULL,
  BROADCASTTEMPLATEGROUPNAME VARCHAR2(50)
);